### ISSUE TITLE
Integreation not works after update

### ISSUE THREAD

**Issue by Cooky-mj** [DeerMaximum/Technische-Alternative-CMI#205]
Hello,

After update to 1.13.1^I see the following message in the logs:

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:496
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 12:23:41 (1 Vorkommnis)
Zuletzt protokolliert: 12:23:41

Error while setting up ta_cmi platform for sensor: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.14/site-packages/homeassistant/helpers/entity_platform.py", line 496, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/home/homeassistant/.homeassistant/custom_components/ta_cmi/sensor.py", line 70, in async_setup_entry
    if dev := device_registry.async_get_device_by_identifier((DOMAIN, ent), entry_id):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier'

**Comment by Cooky-mj** [comment]
Solved after updating HA to 2026.8.2
